services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: database
        ports:
            - '27017:27017'
